### ISSUE TITLE
About the Fusion Module in the paper

### ISSUE THREAD

**Issue by loserhou** [robot-learning-freiburg/BEVCar#1]
Excellent work!I just don't now what the meaning of P in the Fusion module:
<img width="263" alt="1721958731606" src="https://github.com/user-attachments/assets/d62dadd5-6501-495e-a354-66a3e29ba272">
could you explain it?

**Comment by vniclas** [comment]
Hi @loserhou,

I'm extremely sorry for the very late reply. You actually spotted an inconsistency in our manuscript.

"P" should be the same as "f_rad". Please see the latest [arXiv version](https://arxiv.org/abs/2403.11761) for the updated version.
