### ISSUE TITLE
Change number of Camera

### ISSUE THREAD

**Issue by KimJunHan** [robot-learning-freiburg/BEVCar#4]
How to Change number of camera 6 to 3 cam only (Front, Front_left, Front_right)

Just I wanna use 3 camera (Front, Front_left, Front_right)

**Comment by kuersatp** [comment]
Dear Kim,

Since we are providing both the paper and the complete code, implementing the necessary changes should be straightforward. Please put in your best effort, and let us know if you encounter any specific challenges

Best,
Kürsat

**Comment by KimJunHan** [comment]
Now I am change the number of camera 6 to 3 

You use all of 6 camera. CAM_FRONT, CAM_FRONT_RIGHT, CAM_FRONT_LEFT, CAM_BACK, CAM_BACK_LEFT, CAM_BACK_RIGHT

I just encounter specific challenges
we should use just FRONT 3 CAMERA, CAM_FRONT, CAM_FRONT_LEFT, CAM_FRONT_RIGHT.

So. How to remove, Parts of CAM_BACK, CAM_BACK_LEFT, CAM_BACK_RIGHT.

First of all 

I think I should change the nuscenes  GT  MAP Data to use CAM_FRONT three camera parts alongside CAMERA FOV 70 degree


![Image](https://github.com/user-attachments/assets/76581e71-cb60-4be4-a8ef-49d264dd5202)
![Image](https://github.com/user-attachments/assets/ec0b443a-c9cb-4fc3-857b-d0f368ec2977)
![Image](https://github.com/user-attachments/assets/227dce0c-12d2-47db-8869-32964ea8352a)

but I don't know how to remove CAM_BACK, CAM_BACK_RIGHT, CAM_BACK_LEFT parts.

You just put ego vehicle car as green color on the gt_map at the center. 
I think I should move the ego car position from center on map to bottom of the map so that I can remove the all of BACK CAMERA VIEW.

Let me know the way How to remove them.


`def fetch_nusc_map2(rec, nusc_maps, nusc, scene2map, car_from_current):
    egopose = nusc.get('ego_pose', nusc.get('sample_data', rec['data']['LIDAR_TOP'])['ego_pose_token'])

    global_from_car = transform_matrix(egopose['translation'],
                                       Quaternion(egopose['rotation']), inverse=False)

    trans_matrix = reduce(np.dot, [global_from_car, car_from_current])

    rot = np.arctan2(trans_matrix[1, 0], trans_matrix[0, 0])
    center = np.array([trans_matrix[0, 3], trans_matrix[1, 3], np.cos(rot), np.sin(rot)])

    map_name = scene2map[nusc.get('scene', rec['scene_token'])['name']]

    # Debug only:
    # print("Current map: ", map_name)

    poly_names = ['drivable_area', 'carpark_area', 'ped_crossing', 'walkway', 'stop_line']
    line_names = ['road_divider', 'lane_divider']

    # lmap = get_local_map(nusc_maps[map_name], center, 50.0, poly_names, line_names)

    # own labels handling
    # use build in nuscenes function to get binary map mask
    patch_box = (center[0], center[1], 100, 100)  # patch of the map (center_x, center_y, height, width)
    rot_angle = rot * 180 / np.pi  # rotation of the patch -> should match the model output
    # print for console debug
    # print("Car rot angle: ", rot_angle)
    patch_angle = rot_angle  # angle in degrees
    # patch_angle = 0.0  # for debugging only
    canvas_size = (200, 200)  # size of generated output mask -> 200x200
    layer_names = poly_names + line_names
    map_mask = nusc_maps[map_name].get_map_mask(patch_box=patch_box,
                                                patch_angle=patch_angle,
                                                layer_names=layer_names,
                                                canvas_size=canvas_size)

    """ Debug: test if mask is correct:
    figsize = (12, 4)
    fig, ax = nusc_maps[map_name].render_map_mask(patch_box=patch_box,
                                                  patch_angle=patch_angle,
                                                  layer_names=layer_names,
                                                  canvas_size=canvas_size,
                                                  figsize=figsize,
                                                  n_row=1)
    """

    # generate bev view of the ego car for the current patch
    ego_in_bev = np.zeros_like(map_mask[0])

    W = 1.85
    bx = -49.75
    dx = 0.5
    car_points = np.array([[-4.084 / 2. + 1, W / 2.],
                           [4.084 / 2. + 1, W / 2.],
                           [4.084 / 2. + 1, -W / 2.],
                           [-4.084 / 2. + 1, -W / 2.]])

    car_points_scale_shift = (car_points - bx) / dx

    round_car_approx = np.round(car_points_scale_shift)
    x = abs((round_car_approx[0][1] + 1) - round_car_approx[-1][1])
    y = abs(round_car_approx[0][0] - (round_car_approx[1][0] - 1))
    car_mask = np.ones((int(y), int(x)))
    ego_in_bev[int(round_car_approx[0][0]): int(round_car_approx[1][0] - 1),
    int(round_car_approx[-1][1]): int(round_car_approx[0][1] + 1)] = car_mask

    rot_angle = 0.0
    ego_angle = np.arctan2(car_from_current[1, 0], car_from_current[0, 0])
    ego_angle = ego_angle * 180 / np.pi

    bev_plane_rot = ndimage.rotate(ego_in_bev, angle=ego_angle + 90.0, reshape=False)
    egocar_bev = (bev_plane_rot > 0.1).astype(int)

    return map_mask, egocar_bev`

I think I revise the fetch_nusc_map2 function uppper mentioned. Right?

Let me know the way. bro.

thanks 
best regard.
