### ISSUE TITLE
VoxelNet and Point Feature Encoding

### ISSUE THREAD

**Issue by Johnny-Hu-406** [robot-learning-freiburg/BEVCar#5]
Hello,

I was reviewing your work and noticed that you use VoxelNet to extract features from radar data.

In the paper, it mentions using Point Feature Encoding *2.

However, after closely examining the project you released, I couldn’t find the “*2” part.

Could you clarify how this part is implemented?

Thank you!

**Comment by kuersatp** [comment]
Hi,

Our VoxelNet implementation calls the SVFE module, which in turn calls the VFE module twice (with different parameters)

- [SVFE Module](https://github.com/robot-learning-freiburg/BEVCar/blob/978d09c95df0672901a402a6ed729e8936324b51/nets/voxelnet.py#L119)

- [Call of SVFE](https://github.com/robot-learning-freiburg/BEVCar/blob/978d09c95df0672901a402a6ed729e8936324b51/nets/voxelnet.py#L314)
- [VFE Module](
https://github.com/robot-learning-freiburg/BEVCar/blob/978d09c95df0672901a402a6ed729e8936324b51/nets/voxelnet.py#L75C14-L75C20)
