### ISSUE TITLE
multi gpus

### ISSUE THREAD

**Issue by dongpoop** [robot-learning-freiburg/BEVCar#6]
Hello, this is about: I put code on the remote sever, which has two gpus. I modify device_ids = [0,1] in the config file and the same to train.py( main function parameter device_ids), but it still out of memory(each gpu is 24GB and the README.md requires 32GB). What else can I do? Thank you for help!

**Comment by vniclas** [comment]
Hi, 
the 32GB mentioned in the README refers to the required memory per GPU.

Have you also tested with the ResNet setup? That might have a smaller footprint.
