### ISSUE TITLE
Question regarding annotations needed for network

### ISSUE THREAD

**Issue by Yuchen-Tao** [robot-learning-freiburg/BEVCar#8]
Hi, thanks for the amazing work! I am trying to apply this network for some other dataset with camera images and radar point clouds. Could you please explain which labels / annotations are needed for the dataset? Thanks!

**Comment by vniclas** [comment]
Hi, thanks for your interest in our work.

I recommend you have another look at the loss functions defined in the paper and the dataset loader in the file `nuscenes_data.py`. If you still have questions afterward, feel free to re-open this issue.
