### ISSUE TITLE
A problem about nuscenes

### ISSUE THREAD

**Issue by DogZhuaner** [robot-learning-freiburg/BEVCar#9]
When I run the visualization evaluation, I get the error FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Project\\datasets\\scaled_images\\#CUSTOM_RES#\\samples\\CAM_FRONT_LEFT\\n015-2018-08-02-17-16-37+0800__CAM_FRONT_LEFT__1533201470404874.jpg'
. I downloaded the complete nuscenesv1.0 dataset. Why does this error occur? Thank you
![Uploading 1.png…]()

**Comment by vniclas** [comment]
Please look at the `Data Preparation` section in the README. We downsample the image files before training/evaluation to lower the I/O. If you don't need this, feel free to adapt the path to the regular images.
